version: "3.4"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data-mongo:/data/bin:rw

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  server:
    image: node:alpine3.10
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGO_URL: "mongodb://root:password@mongo:27017/app"
      DATABASE_URL: "postgres://root:password@db:5432/app"
    volumes:
      - ./server:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm start --no-update-notifier"

volumes:
  db-data: {}